# Generated by Django 3.2.3 on 2021-06-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('quantidade', models.FloatField()),
                ('tempo', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('imagem', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('file3d', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=250)),
                ('descricao', models.TextField()),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.composicao')),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.imagens')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=250)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.metodo')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=100)),
                ('quantidade', models.FloatField()),
                ('valor_compra', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.material')),
            ],
        ),
        migrations.AddField(
            model_name='composicao',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.material'),
        ),
        migrations.AddField(
            model_name='composicao',
            name='metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loja.metodo'),
        ),
    ]
