# Generated by Django 3.2.3 on 2021-06-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composicao',
            name='material',
        ),
    ]
