# Generated by Django 3.2.3 on 2021-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_auto_20210626_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='desconto',
            field=models.FloatField(default=0.0),
        ),
    ]
