# Generated by Django 3.2.3 on 2026-07-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_auto_20211207_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='descricao',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
