# Generated by Django 3.2.3 on 2026-07-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_auto_20260701_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='composicao',
        ),
        migrations.DeleteModel(
            name='Composicao',
        ),
        migrations.DeleteModel(
            name='Metodo',
        ),
    ]
