# Generated by Django 3.2.3 on 2026-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_auto_20260702_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_material',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tempo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
