# Generated by Django 3.2.3 on 2026-07-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_auto_20260702_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ManyToManyField(blank=True, null=True, to='loja.Imagens'),
        ),
    ]
