# Generated by Django 3.2.3 on 2021-06-20 21:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postagem',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
